apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        volumes:
          - name: ssh-key
            secret:
              secretName: pipeline-autodeploy-key
              defaultMode: 0400
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/nop/pullrequest.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        ### BEGIN CUSTOM STEP
        - name: pyhlml-codescan-step
          image: docker.io/lamatriz/blueprint:scripts_latest
          imagePullPolicy: Always
          resources: {}
          script: |
            #!/bin/bash
            echo "10.0.199.23 utils-sonarqube" >> /etc/hosts
            echo "code scanning"
            sonar-scanner -Dproject.settings=sonar.properties -Dsonar.login=bcbe0d071a62bab52b3e5df6fe8cd4444c0ee149 -Dsonar.host.url=http://utils-sonarqube
        - name: pyhlml-build-step
          image: docker.io/lamatriz/blueprint:scripts_latest
          imagePullPolicy: Always
          resources: {}
          script: |
            #!/bin/bash
            echo "poetry repo config"
            poetry config repositories.genart http://10.3.162.8/artifactory/api/pypi/devpypi
            echo "poetry build & publish"
            poetry publish -r genart --username devpypi --password P@ssw0rd --build
        - name: pyhlml-test-step
          volumeMounts:
            - name: ssh-key
              readOnly: true
              mountPath: /root/.ssh
          image: ubuntu:20.04
          resources: {}
          script: |
            #!/bin/bash
            apt-get update &> .update.log && apt-get -y install openssh-client rsync git &> .install.log
            ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@10.0.199.67 /bin/bash << EOF
                sudo pip3 uninstall -y pyhlml
                sudo pip3 install pyhlml --trusted-host genart
                echo "-------------------"
                echo "test execution"
                echo "-------------------"
                python3 pyhlml-test.py
            EOF
        ### END CUSTOM STEP
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
